# jekyll serve
host: 0.0.0.0

# Build settings
theme: security-onigiri
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - bulma-sass

# Jekyll-assets

assets:
  caching:
    type: memory
    enabled: true

# Jekyll-paginate-v2

pagination:
  per_page: 10
  enabled: true
  permalink: '/:num/'
  title: ':title - 第 :num 頁'
  debug: true
  sort_field: 'date'
  sort_reverse: true

# Theme settings
url: "https://security-onigiri.github.io/"
baseurl: ""
repository: "security-onigiri/security-onigiri.github.io"
disqus_username: bananaappletw
disqus:
  shortname: bananaappletw
google_analytics: UA-115432550-1
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
